### PR TITLE
ggcoxph proposition 

### PR DESCRIPTION
**Pull request by MarcinKosinski**
According to https://github.com/kassambara/survminer/issues/13

Have a look at the proposition of `ggcoxzph`

````{R}
library(survival)
fit <- coxph(Surv(futime, fustat) ~ age + ecog.ps, data=ovarian)
cox.zph.fit <- cox.zph(fit)
ggcoxzph(cox.zph.fit, ggtheme = theme_dark())
````

ggcoxzph

One can think about 
- adding somehow global p-value of the shoenfeld test somewhere to the plot 
- more parameters to extend customization

### CODE REVIEW

**Comment by kassambara** [comment]
Thank you for this great and fast work!

**Comment by kassambara** [comment]
I can work on it for adding some parameters such as:

- point.col,  point.shape
- font.main, font.x, font.y, font.tickslab (as in ggsurvplot)

**Comment by MarcinKosinski** [comment]
Thanks! I would appreciate that if You could extend functionality with new parameters. In such way I could learn something from You :) and maybe in the next pull request I would provide more additional parameters.

**Comment by MarcinKosinski** [comment]
I don't know whether Have You noticed that I Have changed the options of .Rproj file

**Comment by kassambara** [comment]
New arguments added:
- point.col, point.shape, point.size
- font.main, font.x, font.y, font.tickslab

**Comment by MarcinKosinski** [comment]
Great! Thanks for that.

Marcin Kosinski

Dnia 25.02.2016 o godz. 06:56 Alboukadel KASSAMBARA <notifications@github.com> napisał(a):

**Pull request merged**
