### PR TITLE
add option for smooth survival curve in ggsurvplot_df

### PR DESCRIPTION
**Pull request by HeidiSeibold**
This would be a possible solution for issue https://github.com/kassambara/survminer/issues/276. It is just a suggestion. So no pressure.

It is just a feature I really need for my survival course, where I want to use this package and I need to be able to plot survreg models.

I included an example and would be happy to also include something in the vignette if you want.

### CODE REVIEW

**Comment by HeidiSeibold** [comment]
Seems like AppVeyor isn't running.

**Comment by kassambara** [comment]
Thank you @HeidiSeibold for your contribution and sorry for the delay. I will merge this!

**Comment by kassambara** [comment]
Your conntribution in the vignette is also very welcome, thnaks!

**Comment by HeidiSeibold** [comment]
Thanks @kassambara! Should I add to an existing vignette or should there be an additional vignette?

**Comment by kassambara** [comment]
I think that it's better to create an additional vignette for plotting survreg model...

**Pull request merged**
