### PR TITLE
Update ggforest.R

### PR DESCRIPTION
**Pull request by DanChaltiel**
This corrects the bug that made ggforest not displaying polynomial and spline terms, as seen in https://github.com/kassambara/survminer/issues/306.
Of note, I'm confused about the lines 50-51, which are quite long to compute (because `anova()`) but do not seem to add much information (`terms` remained inchanged in all tests I could do). If they do serve some purpose, maybe it could be abstractized into some optional argument ?

### CODE REVIEW

**Comment by pbiecek** [comment]
Thanks! @kassambara would you merge this pull request?

**Comment by DanChaltiel** [comment]
Cool, thanks ! @kassambara but what about lines 50-51? Could you tell me why you want to perform anova here?

**Comment by kassambara** [comment]
@pbiecek is the function `anova()` mandatory for extracting predictor variables in the cox model at line 50-51?

**Comment by pbiecek** [comment]
@kassambara @DanChaltiel thanks for spotting this
this line was added in https://github.com/pbiecek/survminer/commit/1f9bc215e7f4e2b59749ec9a4bf2ada7f5b90da0#diff-97cd488e9c8b8ef57f4181c52a0dc79d

but now I do not see why it is needed. 

I've removed this like and check() is passing, so I will create pull request that removes this line

**Comment by kassambara** [comment]
ok, thanks!

**Pull request merged**
