### PR TITLE
Update ggsurvplot_df.R

### PR DESCRIPTION
**Pull request by BingxinS**
The function .connect2origin() wanted to created and connect each plot to the origin. However, the code basically created and copy the origin for each subplot/faceted plot from the very first one.
I have added a block of code to modify the origin per strata per facet (Line 314-325 added).
A report can be found: https://github.com/BingxinS/survminer-fix

### CODE REVIEW

**Comment by BingxinS** [comment]
Issue reported in https://github.com/kassambara/survminer/issues/254.

Below is my proposed fix:

```{r LoadPackages}
library(survminer)
require("survival")
```

### Test case 1

```{r, echo=FALSE}
# testing dataframe
lungTest <- data.frame ("inst" = c(3, 3, 3, 5, 1, 12, 7, 11, 1, 7), 
                          "time" = c(306, 455, 1010, 210, 883, 1022, 310, 361, 218, 166),
                          "status" = c(2, 2, 1, 2, 2, 1, 2, 2, 2, 2),
                          "age" = c(74, 68, 56, 57, 60, 74, 68, 71, 53, 61),
                          "sex" = c(1, 2, 2, 1, 1, 1, 2, 2, 1, 1),
                          "ph.ecog" = c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2),
                          "ph.karno" = c(90, 90, 90, 90, 100, 50, 70, 60, 70, 70),
                          "pat.karno" = c(100, 90, 90, 60, 90, 80, 60, 80, 80, 70),
                          "meal.cal" = c(1175, 1225, NA, 1150, NA, 513, 384, 538, 825, 271), 
                          "wt.loss" = c(NA, 15, 15, 11, 0, 0, 10, 1, 16, 34)
)
```
which is actural the first 10 data points in lung:
```{r, echo=FALSE}
# testing dataframe
temprcd<-10
lungTest<-lung[1:temprcd,]
```

#### Plot with issues

One can facet the <span style="color:#2980B9">sex=1</span> and <span style="color:#2980B9">sex=2</span> plots by <span style="color:#2980B9">ph.ecog</span> values:
```{r}
survfit(Surv(time, status) ~ sex, lungTest) %>%
    ggsurvplot_facet(lungTest, facet.by="ph.ecog")
```

Image of Yaktocat

Here comes the problem. The function ggsurvplot_facet() missed the first intervals for each survival plot. It was caused by the returning dataframe .$data, where the starting point was not set correctly, shown in the table below. Pay attention to the first 4 rows and the last 2 columns, sex and ph.ecog values are not set correctly, compare to the column strata values.
Image of Yaktocat

#### A fix

The function, that causes the problem of missing the first interval in a survival plot, was function <span style="color:#2980B9">.connect2origin()</span>, which was called by <span style="color:#2980B9">ggsurvplot_df()</span>, which was called by <span style="color:#2980B9">ggsurvplot_core()</span>, which was called by <span style="color:#2980B9">ggsurvplot_facet()</span>. 

The orginial <span style="color:#2980B9">.connect2origin()</span> is as follows:

```{r}
.connect2origin <- function (d, fit, data = NULL) 
{
    base <- d[1, , drop = FALSE]
    base[intersect(c("time", "n.censor", "std.err", "n.event"), 
        colnames(base))] <- 0
    base[c("surv", "upper", "lower")] <- 1
    n.strata <- length(levels(d$strata))
    if (n.strata > 1) {
        strata <- levels(d$strata)
        base <- base[rep(1, n.strata), , drop = FALSE]
        row.names(base) <- 1:nrow(base)
        base$strata <- strata
        base$strata <- factor(strata, levels = strata)
        if (!missing(fit)) {
            if (!inherits(fit, "survfit.cox")) {
                variables <- .get_variables(base$strata, fit, 
                  data)
                for (variable in variables) base[[variable]] <- .get_variable_value(variable, 
                  base$strata, fit, data)
            }
        }
    }
    d <- rbind(base, d)
    d
}
```
The code basically created and copy the origin for each subplot/faceted plot from the very first one. 

I have added a block of code to modify the origin per strata per facet as follows as <span style="color:#2980B9">.connect2origin_fix()</span>:

```{r}
.connect2origin_fix <- function(d, fit, data = NULL){

  base <- d[1, , drop = FALSE]
  base[intersect(c('time', 'n.censor', 'std.err', "n.event"), colnames(base))] <- 0
  base[c('surv', 'upper', 'lower')] <- 1.0
  n.strata <- length(levels(d$strata))
  
  # Connect each group to the origin
  if (n.strata > 1) {
    strata <- levels(d$strata)
    base <- base[rep(1, n.strata),, drop = FALSE]
    row.names(base) <- 1:nrow(base)
    base$strata <- strata
    base$strata <- factor(strata, levels = strata)
    
    #############################################################
    ##   added to modify values for each strata and facet      ##
    indStrata <- grep("strata",names(base))
    indMax    <- length(names(base))
    if(indStrata<indMax & n.strata>0){
      for (indRow in c(1:n.strata)) {
        tmpStrata = as.list(strsplit(strata[indRow], '\\,'))[[1]]
        tmpFacet  = as.numeric(gsub("\\D", "", tmpStrata)) 
        base[indRow, c((indStrata+1):indMax)] = tmpFacet
      }
    }
    ##                ending of the modification               ##
    #############################################################
    
    # update variable values
    if(!missing(fit)){
      if(!inherits(fit, "survfit.cox")){
        variables <- .get_variables(base$strata,  fit, data)
        for(variable in variables) base[[variable]] <- .get_variable_value(variable, base$strata, fit, data)
      }
    }
  }
  d <- rbind(base, d)
  d
}
```

Now the fixed table is as:
Image of Yaktocat
The fixed survival plot is as:
Image of Yaktocat

### Test case 2
This case is with more choices of strata and facets. Note that there is no data points for certain strata and facet.

```{r}
require("survival")
temprcd<-100
lungTest<-lung[1:temprcd,]

# original ggsurvplot_facet missed the first intervals for each survival plot
survfit(Surv(time, status) ~  sex, lungTest) %>%
  ggsurvplot_facet(lungTest, facet.by=c("ph.ecog", "ph.karno"))
```
Image of Yaktocat

```{r}
# fixed plot
survfit(Surv(time, status) ~  sex, lungTest) %>%
  ggsurvplot_facet_fix(lungTest, facet.by=c("ph.ecog", "ph.karno"))
```
Image of Yaktocat

**Comment by BingxinS** [comment]
@kassambara 

Dear Alboukadel,

Would you please review this pull request?
Our colleagues at BMS (Bristol-Myers Squibb) are using the fixed version already.
We are wondering if you would prove/merge the pull request, how soon this update would be ready on CRAN for them to update the package.
Thank you! Really appreciate your wonderful work.

Bingxin Shen

**Comment by kassambara** [comment]
We can finally simplify the `.connect2origin()` function as follow:


```r
.connect2origin <- function(d, ...){
  n.risk <- strata <- NULL
  if("n.risk" %in% colnames(d)){d <- dplyr::arrange(d, dplyr::desc(n.risk))}
  origin <- d %>% distinct(strata, .keep_all = TRUE)
  origin[intersect(c('time', 'n.censor', 'std.err', "n.event"), colnames(origin))] <- 0
  origin[c('surv', 'upper', 'lower')] <- 1.0
  dplyr::bind_rows(origin, d)
}
```

**Comment by kassambara** [comment]
Fixed now, thanks!

Install the latest developmental version and test this:

```r
df <- structure(list(ID = c("897", "838", "839", "847", "842", "801", 
"718", "726", "730", "925", "926", "931", "936", "952", "953", 
"884", "891", "894", "895", "899", "902", "905", "908", "914", 
"807", "841", "844", "837", "846", "815", "818", "819", "822", 
"800", "722", "728", "809", "892", "900", "724", "885", "939", 
"940", "946", "810", "943", "934", "840", "947", "727", "937", 
"955", "954", "948", "889", "935", "929", "798", "716", "816", 
"824"), gender = structure(c(2L, 1L, 1L, 2L, 2L, 1L, 2L, 2L, 
2L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 2L, 
1L, 1L, 2L, 1L, 2L, 1L, 2L, 2L, 2L, 1L, 2L, 2L, 1L, 1L, 1L, 1L, 
1L, 2L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 1L, 2L, 2L, 
2L, 1L, 1L, 1L, 2L), .Label = c("Female", "Male"), class = "factor"), 
    genotype = structure(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 2L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 2L, 2L, 2L, 2L), .Label = c("+/+/-", "+/+/+"), class = "factor"), 
    survival = c(122L, 394L, 394L, 394L, 394L, 400L, 401L, 401L, 
    401L, 519L, 519L, 519L, 519L, 519L, 519L, 520L, 520L, 520L, 
    520L, 520L, 520L, 520L, 520L, 520L, 72L, 394L, 394L, 394L, 
    394L, 399L, 399L, 399L, 399L, 400L, 401L, 401L, 75L, 78L, 
    80L, 83L, 87L, 106L, 106L, 113L, 123L, 125L, 126L, 134L, 
    143L, 151L, 164L, 171L, 203L, 226L, 239L, 379L, 407L, 88L, 
    124L, 159L, 299L), censor = c(0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 
    0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 0L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 
    1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L)), row.names = c(NA, -61L
), class = "data.frame", .Names = c("ID", "gender", "genotype", 
"survival", "censor"))

library(survival)
library(survminer)

fit  <- survfit(Surv(survival, censor) ~ gender + genotype, data = df)

ggsurvplot(fit, facet.by="gender")
````

Should give this output:

rplot

**Pull request closed without merging**
