### PR TITLE
better coordinates for vignette for wieghted log-rank tests

### PR DESCRIPTION
**Pull request by MarcinKosinski**
@kassambara One more update for #127 #17

### CODE REVIEW

**Comment by kassambara** [comment]
R CMD CHECK generated an error:

Error: Vignette 'Specifiying_weights_in_log-rank_comparisons.Rmd' is non-ASCII but has no declared encoding

Any idea for fixing this?

**Comment by MarcinKosinski** [comment]
@kassambara maybe my surname

**Comment by MarcinKosinski** [comment]
Ok it's the reference

````{R}
> x <- readLines('vignettes/Specifiyng_weights_in_log-ran_comparisons.Rmd')
> tools::showNonASCII(x)
152: - Gehan A. A Generalized Wilcoxon Test for Comparing Arbitrarily Singly-Censored Samples. Biometrika 1965 Jun. 52(1/2):203<e2><80><93>23. [JSTOR](www.jstor.org/stable/2333825)
154: - Tarone RE, Ware J 1977 On Distribution-Free Tests for Equality of Survival Distributions. Biometrika;64(1):156<e2><80><93>60. [JSTOR](http://www.jstor.org/stable/2335790)
156: - Peto R, Peto J 1972 Asymptotically Efficient Rank Invariant Test Procedures. J Royal Statistical Society 135(2):186<e2><80><93>207. [JSTOR](http://www.jstor.org/stable/2344317)
158: - Fleming TR, Harrington DP, O'Sullivan M 1987 Supremum Versions of the Log-Rank and Generalized Wilcoxon Statistics. J American Statistical Association 82(397):312<e2><80><93>20. [JSTOR](http://www.jstor.org/stable/2289169)
````

**Comment by MarcinKosinski** [comment]
fix is in the #130

**Pull request merged**
