### PR TITLE
candidate solution for #229

### PR DESCRIPTION
**Pull request by pbiecek**
These changes are related to #229 and partially to #227 

I've added a new function `ggadjustedcurves()` to replace `ggcoxadjustedcurves()` (right now left unchanged to make it easier to compare these two.
This function as additional argument `method` that handles four different approaches, `single` and `average` was two implemented previously in `ggcoxadjustedcurves()` (but now are more efficient) while `conditional` and `marginal` are new different approaches to balance the data.

The description is updated and extended. More examples are provided.

Next steps: (1) remove `ggcoxadjustedcurves()` (2) update NOTES (3) add risktable and medium survival to `ggadjustedcurves()`

### CODE REVIEW

**Comment by kassambara** [comment]
Thank you!!!

**Comment by sdesai90** [comment]
Many thanks for the update! Has the package been updated with the new function? Currently I don't see any updates or the new function "ggadjustedcurves"?

Thanks again

**Comment by pbiecek** [comment]
Hi, according to https://github.com/kassambara/survminer/blob/master/NEWS.md
there was an update in version 0.4.0.999
On CRAN there is still version 0.4.0 so maybe this is why you do not see these changes
Please install from GitHub with following line:
```
devtools::install_github("kassambara/survminer")
```

**Comment by sdesai90** [comment]
Thanks, I appreciate the prompt responses.

Sameer

**Comment by sdesai90** [comment]
Hello,

First off thanks for all the work on the survminer and ggpubr packages for R! They’ve been an awesome addition to my list of r packages to use! 

A few months ago I built a survival curve using these packages and it worked fine…I need to tweak a few things and now it doesn’t seem to work. 

a = ggsurvplot(km.as.one,
                 data = baseline_ready,
                 xlab="Time from CF diagnosis to death or transplant (years)",
                 ylab="Lung Transplant-Free Survival Probability",
                 ggtheme = theme_light(),palette = "black",
                 break.x.by=5,
                 font.main=15,
                 legend="none") 
a + scale_y_continuous(expand = c(0, 0), limits = c(0, 1.00)) +
  geom_segment(aes(x=10,y=0,xend=10,yend=0.877),color="red") +
  geom_segment(aes(x=15,y=0,xend=15,yend=0.861),color="red") +
  geom_segment(aes(x=5,y=0,xend=5,yend=0.92),color="red") +
    annotate("text", x = 7, y=0.85, label = "10-year survival 87.7%", colour = "black", size = 3,fontface = "italic") +
    annotate("text", x = 7, y=0.81, label = "(95% CI: 82.9%, 91.3%)", colour = "black", size = 2.5,fontface = "italic") +
    annotate("text", x = 14, y=0.70, label = "15-year survival 86.1%", colour = "black", size = 3,fontface = "italic") +
    annotate("text", x = 14, y=0.66, label = "(95% CI: 80.7%, 90.1%)", colour = "black", size = 2.5,fontface = "italic")


I get this error: 
Error in a + scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) : 
  non-numeric argument to binary operator
In addition: Warning message:
Incompatible methods ("+.ggsurv", "+.gg") for "+" 

It has something to do with the + operator but I don’t have the expertise to debug this, especially since it worked before and I produced really nice plots!


Any help will be appreciated, thanks!

Sameer

**Pull request merged**
