### PR TITLE
Proposed fix for #317

### PR DESCRIPTION
**Pull request by krassowski**
This fixes the problem for me, but possibly a more comprehensive solution, dealing with other, similar parameters might be needed in future.

### CODE REVIEW

**Comment by MarcinKosinski** [comment]
@krassowski the travis check didnt pass. Can you verify?

Thanks for the contribution!

**Comment by krassowski** [comment]
Sure. I forgot to update generate docs. It passes now.

**Comment by kassambara** [comment]
Thanks @krassowski!!

**Comment by kassambara** [comment]
Thank you @krassowski for your contribution! Merged now.

**Pull request merged**
